receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 50
  memory_limiter:
    limit_mib: 512

exporters:
  prometheus:
    endpoint: '0.0.0.0:8889'
    namespace: 'handler'
    const_labels:
      environment: 'development'

  logging:
    loglevel: debug

  # Export traces to Sentry (if configured)
  # sentry:
  #   dsn: "${SENTRY_DSN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, logging]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [logging]

  extensions: []
