name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read .nvmrc
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      # Setup pnpm before Node.js. This action makes the `pnpm` command available.
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      # Setup Node.js using the version from .nvmrc and enable caching for pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint Code
        run: pnpm lint

      - name: Type Check
        run: pnpm tsc --noEmit

      - name: Build Projects
        run: pnpm build

      - name: Run Tests
        run: pnpm test

      - name: Security Audit
        run: pnpm audit --audit-level=high
